# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.7
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: surabhipatel2803@gmail.com
author_name: sur03
contract_name: paychain
preset_name: starter
project_name: campuschain-contracts

